name: Run Python Script

on:
  schedule:
    - cron: '0 * * * *'  # This will run the script every hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: List files in directory (Debugging step)
        run: |
          ls -al

      - name: Print Python version (Debugging step)
        run: |
          python --version

      - name: Run script
        env:
          TICKETMASTER_API_KEY: ${{ secrets.TICKETMASTER_API_KEY }}
          MAILGUN_USERNAME: ${{ secrets.MAILGUN_USERNAME }}
          MAILGUN_PASSWORD: ${{ secrets.MAILGUN_PASSWORD }}
        run: |
          python main.py  # Replace with the path to your script
